server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: client_route
          uri: ${CLIENT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/clients/**


        - id: invoice_route
          uri: ${INVOICE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/invoices/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:8090"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
